### ISSUE TITLE
current user

### ISSUE THREAD

**Issue by drgarcia1986** [klen/muffin-session#1]
Is it safe to use `muffin.local` to store the current user?
I look for a way to get current user and use it in a `jinja2 context_processor`.
In [cookiecutter-muffin](https://github.com/drgarcia1986/cookiecutter-muffin) I created [middleware_current_user](https://github.com/drgarcia1986/cookiecutter-muffin/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/common/middlewares.py#L7-L22) to store the current user in `muffin.local` and use this information in [current_user_context](https://github.com/drgarcia1986/cookiecutter-muffin/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/common/utils.py#L6-L10). If this is ok, I can open a pull request with this features in `muffin-session` and `muffin-jinja2`

**Comment by klen** [comment]
Unfortunately, It's not safe. For most cases — yes. But you need to know about exceptions (asyncio.wait, asyncio.wait_for). I'll write about later.
